---
title: "ShareRepurchase_Quarterly_Analysis"
output: html_document
date: "2024-08-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data Cleaning
```{r}
library(data.table)
library(dplyr)
library(haven)
library(stringr)
library(mvtnorm)
library(tidyr)
library(readxl)
library(ggplot2)
library(patchwork) # To display 2 charts together
library(hrbrthemes) # For ggplot2 themes
library(stargazer) # For regression tables

options(scipen = 999)
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

rm(list = ls())
```

```{r}
# MERGE in TR 13F data on institutional holdings 
# Read the csv dataset in the current folder
data_tr <- fread("../Data/tr_13f.csv")
# check the first few rows
head(data_tr)
# generate fyearq fqtr using rdate
data_tr <- data_tr %>%
  mutate(fyearq = year(rdate),
         fqtr = ifelse(month(rdate) %in% 1:3, 1, ifelse(month(rdate) %in% 4:6, 2, ifelse(month(rdate) %in% 7:9, 3, 4)))
  )

# check manually for JPM
tr_check <- data_tr %>%
  filter(ticker == "JPM") 
tr_check_filtered <- tr_check %>%
  group_by(ticker, fyearq, fqtr) %>%
  filter(InstOwn_Perc == max(InstOwn_Perc)) %>%
  ungroup()

# select the row with the larger InstOwn_Percent by ticker fyearq fqtr in case of duplicates
data_tr <- data_tr %>%
  group_by(ticker, fyearq, fqtr) %>%
  filter(InstOwn_Perc == max(InstOwn_Perc)) %>%
  ungroup()

# rename ticker to tic
data_tr <- data_tr %>%
  rename(tic = ticker)
```


```{r}
# Generate Dividend and Repurchase for each gvkey fyearq fqtr

compustat <- fread("../Data/compustat_quarterly.csv")
# Put the variable gvkey fyearq fqtr dvpy dividend dvp repurchase repurchase_a repurchase_q in front 
data <- compustat %>%
  dplyr::select(gvkey, tic, fyearq, fqtr, atq, capr1q, capr1, niq, ibq, req, dvpy, dvc, dvy, tstkq, tstk, prstkcy, sstky, prstkc, sstk, naicsh, conm, fic)

# make sure the panel is balanced with no missing year-quarter 
data <- data %>%
  complete(gvkey, fyearq, fqtr = 1:4)
# check for observation with fqtr == 1,2,3,4 respectively (print out the results)
data %>%
  group_by(fqtr) %>%
  summarise(total = n())
# fill atq as previous or next quarter if atq is NA
data <- data %>%
  group_by(tic) %>%
  arrange(tic, fyearq, fqtr) %>%
  mutate(atq = ifelse(is.na(atq), lag(atq, 1), atq))
data <- data %>%
  group_by(tic) %>%
  arrange(tic, fyearq, fqtr) %>%
  mutate(atq = ifelse(is.na(atq), lead(atq, 1), atq))
# fill dvy as previous quarter dvy if dvy is NA or 0
data <- data %>%
  group_by(tic, fyearq) %>%
  arrange(tic, fyearq, fqtr) %>%
  mutate(dvy = ifelse(is.na(dvy) | dvy == 0, lag(dvy, 1), dvy))

# note that quarterly dividend is the difference between the current quarter and the previous quarter amount
# for each given gvkey fyearq
# generate the quarterly dividend amount

# generate dividend that is the difference between current period and last period dividend for each ticker year quarter
data <- data %>%
  group_by(tic) %>%
  arrange(tic, fyearq, fqtr) %>%
  mutate(dividend = dvy - lag(dvy, 1))
# replace dividend = dvy if fqtr = 1
data <- data %>%
  mutate(dividend = ifelse(fqtr == 1, dvy, dividend))

# fill tstkq = 0 if na
data <- data %>%
  mutate(tstkq = ifelse(is.na(tstkq), 0, tstkq))
# generate quarterly repurchase amount
data <- data %>%
  group_by(tic) %>%
  arrange(tic, fyearq, fqtr) %>%
  mutate(repurchase = tstkq - lag(tstkq, 1))
# replace repurchase as prstkcy - sstky if repurchase is 0 or NA
# replace prstkcy and sstky to be the difference between the current and last quarter
data <- data %>%
  group_by(tic) %>%
  arrange(tic, fyearq, fqtr) %>%
  mutate(prstkcy1 = prstkcy - lag(prstkcy, 1),
         sstky1 = sstky - lag(sstky, 1))
data <- data %>%
  mutate(prstkcy1 = ifelse(fqtr == 1, prstkcy, prstkcy1),
         sstky1 = ifelse(fqtr == 1, sstky, sstky1))

data <- data %>%
  mutate(repurchase = ifelse(repurchase == 0 | is.na(repurchase), prstkcy1 - sstky1, repurchase))
# set repurchase as 0 if repurchase < 0
data <- data %>%
  mutate(repurchase = ifelse(repurchase < 0, 0, repurchase))
# set dividend as 0 if dividend < 0
data <- data %>%
  mutate(dividend = ifelse(dividend < 0, 0, dividend))
# arrange data to view the data
data <- data %>%
  arrange(tic, fyearq, fqtr) %>% 
  select(tic, fyearq, fqtr, tstkq, tstk, prstkcy, sstky, prstkcy1, sstky1, repurchase, dvpy, dvc, dvy, dividend, everything())

# keep only those with valid ticker (drop those with "")
data <- data %>%
  filter(tic != "")
data_tr <- data_tr %>%
  filter(tic != "")

# merge the two datasets using ticker and fyearq-fqtr
data <- merge(data, data_tr, by = c("tic", "fyearq", "fqtr"), all.x = TRUE)
# check if tic fyearq fqtr is key
data %>%
  dplyr::select(tic, fyearq, fqtr) %>%
  unique()

# replace NA to 0 for share repurchase and dividend
data <- data %>%
  mutate(repurchase = ifelse(is.na(repurchase), 0, repurchase),
         dividend = ifelse(is.na(dividend), 0, dividend))

# keep only the firms with naics == 522110
data <- data %>%
  filter(naicsh == 522110)

# divide dividends and share-repurchase and assets by 1,000 to make units $Billion
data <- data %>%
  mutate(dividend = dividend / 1000,
         repurchase = repurchase / 1000,
         atq = atq / 1000,
         niq = niq / 1000)

# Generate the share repurchase dummy == 1 if repurchase> 0
data <- data %>%
  mutate(repurchase_dummy = ifelse(repurchase > 0, 1, 0))
# Generate the dividend dummy == 1 if dividend > 0
data <- data %>%
  mutate(dividend_dummy = ifelse(dividend > 0, 1, 0))

# drop foreign banks
data <- data %>%
  filter(fic == "USA")

```

```{r}
# loan inflation data to adjust for inflation
inflation <- fread("../Data/cpi_quarterly_1988to2023.csv")
colnames(inflation) <- c("date", "cpi")
inflation <- inflation %>%
  mutate(fyearq = year(date),
         fqtr = quarter(date))
# merge the inflation data with the data
data_cpi_adjusted <- merge(data, inflation, by = c("fyearq", "fqtr"), all.x = TRUE)
# adjust the repurchase and dividend and asset for inflation
data_cpi_adjusted <- data_cpi_adjusted %>%
  mutate(repurchase = repurchase / cpi * 100,
         dividend = dividend / cpi * 100,
         atq = atq / cpi * 100,
         niq = niq / cpi * 100)
```

```{r}
# Figure 1: General Trends of Share Repurchase/Dividend Payout from 1988-current
# Generate the total sum of dividends and repurchases for each fyearq-fqtr
# as well as the total number of firms that issues dividends or repurchase in that year-quarter

# keep only years after 2003
data_cpi_adjusted <- data_cpi_adjusted %>%
  filter(fyearq >= 2004) %>%
  filter(atq >= 10)

# generate a year-quarter variable from fyearq and fqtr
data_cpi_adjusted <- data_cpi_adjusted %>%
  mutate(date = as.Date(paste0(fyearq, "-", fqtr * 3, "-01")))

data1 <- data_cpi_adjusted %>%
  group_by(fyearq) %>%
  summarise(total_dividend = sum(dividend, na.rm = TRUE),
            total_repurchase = sum(repurchase, na.rm = TRUE),
            total_firms = n(), 
            total_dividend_firms = sum(dividend_dummy, na.rm = TRUE),
            total_repurchase_firms = sum(repurchase_dummy, na.rm = TRUE),
            )
# plot the times series trend of share repurchase and dividend sums in the same ggplot (overlay plot))
# keep only total dividend and total repurchase
total_div_repur <- dplyr::select(data1, c('fyearq','total_dividend','total_repurchase')) %>%
  gather(key = "method", value = "value", -fyearq)
total_div_repur %>%
  ggplot(aes(x = fyearq, y = value, color = method)) +
  geom_line() +
  geom_point() +
  labs(title = "Total Dividends and Share Repurchase by Commercial Banks",
       x = "Year",
       y = "Total Dividends and Share Repurchase ($billion)",
       color = "Method") +
  scale_color_manual(values = c("total_dividend" = "red", "total_repurchase" = "blue")) +  # Custom colors
  theme_minimal() +
  theme(legend.position = "top")
# save to Results folder as pdf
ggsave("../Results/Total_Div_Repur_Banks.pdf")

# Plot the share of firms that issue dividends or repurchase using the same method as above
# generate share of firms that issue dividends or repurchase
data1 <- data1 %>%
  mutate(share_dividend_firms = total_dividend_firms / total_firms,
         share_repurchase_firms = total_repurchase_firms / total_firms)

share_div_repur <- dplyr::select(data1, c('fyearq','share_dividend_firms','share_repurchase_firms')) %>%
  gather(key = "method", value = "value", -fyearq)
share_div_repur %>%
  ggplot(aes(x = fyearq, y = value, color = method)) +
  geom_line() +
  geom_point() +
  labs(title = "Share of Banks that Issue Dividends and Share Repurchase",
       x = "Year",
       y = "Share of Banks that Issue Dividends and Share Repurchase",
       color = "Method") +
  scale_color_manual(values = c("share_dividend_firms" = "red", "share_repurchase_firms" = "blue")) +  # Custom colors
  theme_minimal() +
  theme(legend.position = "top")
# save to Results folder as pdf
ggsave("../Results/Share_Div_Repur_Banks.pdf")
```

```{r}
# Generate categorial variable for banks larger than $700 billion in assets, between $100 billion and $700 billion, and between $100 billion and $10 billion
data_final <- data_cpi_adjusted %>% filter(atq > 10)
data_final <- data_final %>%
  mutate(size = ifelse(atq > 700, 3, ifelse(atq > 100, 2, 1)))

# generate new variable size_prev_quarter 
data_final <- data_final %>%
  group_by(tic) %>%
  mutate(size_prev_quarter = lag(size, 1))
# drop if size_prev_quarter is NA
data_final <- data_final %>%
  filter(!is.na(size_prev_quarter))
# label the size variable
data_final <- data_final %>%
  mutate(size_prev_quarter = ifelse(size_prev_quarter == 1, "Regional", ifelse(size_prev_quarter == 2, "Large", "G-SIB")))

# Figure 2: Share Repurchase and Dividend by Buckets of Bank Sizes
# plot the total dividend and repurchase for different size buckets by fyearq
data1_size <- data_final %>%
  group_by(fyearq, size_prev_quarter) %>%
  summarise(total_dividend = sum(dividend, na.rm = TRUE),
            total_repurchase = sum(repurchase, na.rm = TRUE),
            total_firms = n(), 
            total_dividend_firms = sum(dividend_dummy, na.rm = TRUE),
            total_repurchase_firms = sum(repurchase_dummy, na.rm = TRUE),
            )

# plot the times series trend of share repurchase and dividend sums in the same ggplot (overlay plot))
# keep only total dividend and total repurchase
total_div_repur_size <- dplyr::select(data1_size, c('fyearq','total_dividend','total_repurchase', 'size_prev_quarter')) %>%
  gather(key = "method", value = "value", -fyearq, -size_prev_quarter)
total_div_repur_size %>%
  ggplot(aes(x = fyearq, y = value, color = method)) +
  geom_line() +
  geom_point() +
  facet_wrap(~size_prev_quarter) +
  labs(title = "Total Dividends and Share Repurchase by Commercial Banks",
       x = "Year",
       y = "Total Dividends and Share Repurchase ($billion)",
       color = "Method") +
  scale_color_manual(values = c("total_dividend" = "red", "total_repurchase" = "blue")) +  # Custom colors
  theme_minimal() +
  theme(legend.position = "top")
# save figure
ggsave("../Results/Total_Div_Repur_Banks_Size.pdf")
```

```{r}
# keep only year 2020 of data_final
data_final_2020 <- data_final %>%
  filter(fyearq == 2020)
# keep fqtr == 4
data_final_2020 <- data_final_2020 %>%
  filter(fqtr == 4)
# keep only fyearq tic gvkey cusip conm
data_final_2020 <- data_final_2020 %>%
  dplyr::select(fyearq, tic, gvkey, cusip, conm, size_prev_quarter)
# export to csv
write.csv(data_final_2020, "../Data/data_final_2020.csv")
```

```{r}
### New Plots with Institutional Holdings and Capr1 Ratio Overlayed with Total Dividends and Share Repurchase
# Figure 4 AND 5

# keep only those observations with valid institutional holdings (non-NA InstOwn_Perc) and capr1q and asset
data_final_clean <- data_final %>%
  filter(!is.na(InstOwn_Perc)) %>%  filter(!is.na(atq))
# get rid of negative values in capr1q and those with > 100 capr1q
data_final_clean <- data_final_clean %>% filter(capr1q >= 0) %>% filter(capr1q <= 100)
# get rid of InstOwn_Perc that are larger than 1
data_final_clean <- data_final_clean %>%
  filter(InstOwn_Perc <= 1)

# generate total dividends/repurchase, share repurchase/dividend, and share of firms that issue dividends/repurchase, and InstOwn_Perc
data_inst1 <- data_final_clean %>%
  group_by(fyearq) %>%
  summarise(total_dividend = sum(dividend, na.rm = TRUE),
            total_repurchase = sum(repurchase, na.rm = TRUE),
            total_firms = n(), 
            total_dividend_firms = sum(dividend_dummy, na.rm = TRUE),
            total_repurchase_firms = sum(repurchase_dummy, na.rm = TRUE),
            avg_inst = mean(InstOwn_Perc, na.rm = TRUE),
            avg_capr1q = mean(capr1q, na.rm = TRUE))

# plot the times series trend of share repurchase and dividend sums in the same ggplot (overlay plot))
# keep only total dividend and total repurchase

ggplot(data_inst1, aes(x = fyearq)) +
  geom_line(aes(y = total_repurchase, color = "Total Share Repurchase")) +
  geom_line(aes(y = total_dividend, color = "Total Dividend")) +
  geom_line(aes(y = avg_inst * 100, color = "Institutional Ownership")) +
  geom_line(aes(y = avg_capr1q, color = "Tier 1 Capital Ratio")) +
  scale_y_continuous(
    name = "Total Amount ($billion)",
    sec.axis = sec_axis(~./100, name = "Ratio")
  ) +
  scale_color_manual(
    values = c(
      "Total Share Repurchase" = "blue",
      "Total Dividend" = "red",
      "Institutional Ownership" = "purple",
      "Tier 1 Capital Ratio" = "green"
    )
  ) + 
  labs(color = "Legend") +
  xlab("Year") + 
  theme_minimal() +
  theme(legend.position = "top")
# Save to Results folder as pdf
ggsave("../Results/Total_Div_Repur_Inst.pdf")

# Do the same as above but keeping only the GSIBS/Large/Regional Banks
data_inst1_size <- data_final_clean %>%
  group_by(fyearq, size_prev_quarter) %>%
  summarise(total_dividend = sum(dividend, na.rm = TRUE),
            total_repurchase = sum(repurchase, na.rm = TRUE),
            total_firms = n(), 
            total_dividend_firms = sum(dividend_dummy, na.rm = TRUE),
            total_repurchase_firms = sum(repurchase_dummy, na.rm = TRUE),
            avg_inst = mean(InstOwn_Perc, na.rm = TRUE),
            avg_capr1q = mean(capr1q, na.rm = TRUE))

# plot the times series trend of share repurchase and dividend sums in the same ggplot (overlay plot))
# keep only total dividend and total repurchase

ggplot(data_inst1_size, aes(x = fyearq)) +
  geom_line(aes(y = total_repurchase, color = "Total Share Repurchase")) +
  geom_line(aes(y = total_dividend, color = "Total Dividend")) +
  geom_line(aes(y = avg_inst * 100, color = "Institutional Ownership")) +
  geom_line(aes(y = avg_capr1q, color = "Tier 1 Capital Ratio")) +
  scale_y_continuous(
    name = "Total Amount ($billion)",
    sec.axis = sec_axis(~./100, name = "Ratio")
  ) +
  scale_color_manual(
    values = c(
      "Total Share Repurchase" = "blue",
      "Total Dividend" = "red",
      "Institutional Ownership" = "purple",
      "Tier 1 Capital Ratio" = "green"
    )
  ) +
  labs(color = "Legend") +
  xlab("Year") + 
  theme_minimal() +
  theme(legend.position = "top") +
  facet_wrap(~size_prev_quarter)
# Save to Results folder as pdf
ggsave("../Results/Total_Div_Repur_Inst_Banks_Size.pdf")

```
```{r}
# generate quarterly charts for institutional ownership for three bank cohorts from Q1 2007 to Q4 2010 and Q3 2022 to Q2 2024
# generate year-quarter date from fyearq and fqtr
data_final_clean <- data_final_clean %>%
  mutate(date = as.Date(paste0(fyearq, "-", fqtr * 3, "-01")))
data_inst_quarterly_fin <- data_final_clean %>%
  filter(fyearq >= 2007 & fyearq <= 2010) %>%
  group_by(date, size_prev_quarter) %>%
  summarise(avg_inst = mean(InstOwn_Perc, na.rm = TRUE))
# plot the times series trend of institutional ownership for three cohorts in the same ggplot (overlay plot))
ggplot(data_inst_quarterly_fin, aes(x = date, y = avg_inst * 100, color = size_prev_quarter)) +
  geom_line() +
  geom_point() +
  labs(title = "Institutional Ownership by Bank Size",
       x = "Year",
       y = "Institutional Ownership (%)",
       color = "Size") +
  theme_minimal() +
  theme(legend.position = "top")
ggsave("../Results/Avg_Inst_BankSize_2007to2010.pdf")

data_inst_quarterly_covid <- data_final_clean %>%
  filter(fyearq >= 2022 & fyearq <= 2024) %>%
  group_by(date, size_prev_quarter) %>%
  summarise(avg_inst = mean(InstOwn_Perc, na.rm = TRUE))
# plot the times series trend of institutional ownership for three cohorts in the same ggplot (overlay plot))
ggplot(data_inst_quarterly_covid, aes(x = date, y = avg_inst * 100, color = size_prev_quarter)) +
  geom_line() +
  geom_point() +
  labs(title = "Institutional Ownership by Bank Size",
       x = "Year",
       y = "Institutional Ownership (%)",
       color = "Size") +
  theme_minimal() +
  theme(legend.position = "top")
ggsave("../Results/Avg_Inst_BankSize_2022to2024.pdf")

data_inst_quarterly <- data_final_clean %>%
  group_by(date, size_prev_quarter) %>%
  summarise(avg_inst = mean(InstOwn_Perc, na.rm = TRUE))
# plot the times series trend of institutional ownership for three cohorts in the same ggplot (overlay plot))
ggplot(data_inst_quarterly, aes(x = date, y = avg_inst * 100, color = size_prev_quarter)) +
  geom_line() +
  geom_point() +
  labs(title = "Institutional Ownership by Bank Size",
       x = "Year",
       y = "Institutional Ownership (%)",
       color = "Size") +
  theme_minimal() +
  theme(legend.position = "top")
ggsave("../Results/Avg_Inst_BankSize_1988to2024.pdf")

```

```{r}
### Regressions with data_inst (Institutional Ownership) and Share Repurchase Behavior 

# change institutional ownership to percentage
data_reg_ready <- data_final_clean %>%
  mutate(capr1q = capr1q / 100)
### Summary Statistics

# make sure the panel is balanced, ie. there is no gap between year quarter; fill in the missing year-quarter with NA values
data_reg_ready <- complete(data_reg_ready, nesting(fyearq, fqtr, gvkey))

# Generate change in institutional ownership as the difference between current period and last period ownership percentage
data_reg_ready <- data_reg_ready %>%
  group_by(tic) %>%
  mutate(InstOwn_Perc_Lag = lag(InstOwn_Perc)) %>%
  ungroup() %>%
  #mutate(InstOwn_Perc_Lag = ifelse(is.na(InstOwn_Perc_Lag), 0, InstOwn_Perc_Lag)) %>%
  mutate(Delta_Institutional_Ownership = InstOwn_Perc - InstOwn_Perc_Lag)
# Generate lagged variable for delta institutional ownership
data_reg_ready <- data_reg_ready %>%
  group_by(tic) %>%
  mutate(Lag_Delta_Institutional_Ownership = lag(Delta_Institutional_Ownership)) 

# generate dividend dummy
data_reg_ready <- data_reg_ready %>%
  mutate(Dividend_Dummy = ifelse(dividend > 0, 1, 0))

# Rename the variables to make them more readable
data_reg_ready <- data_reg_ready %>%
  rename(ShareRepurchase_Amount = repurchase,
         Dividend_Amount = dividend,
         ShareRepurchase_Dummy = repurchase_dummy,
         Total_Assets = atq,
         Tier1Capital_Ratio = capr1q,
         Institutional_Ownership = InstOwn_Perc,
         Lag_Institutional_Ownership = InstOwn_Perc_Lag,
         Net_Income = niq,
         )

# output summary statistics of main regression variables including 
# share repurchase dummy, share repurchase amount, atq, capr1q, and InstOwn_Perc and output to a text file
# Rename InstOwn_Perce as it's too long for stargazer

### Regression Results

data_reg_ready <- as.data.frame(data_reg_ready)
# check if data_inst is a data frame
is.data.frame(data_reg_ready)

# drop if we have NA in the variables
data_reg_ready <- data_reg_ready %>%
  drop_na(ShareRepurchase_Dummy, ShareRepurchase_Amount, Dividend_Amount, Total_Assets, Tier1Capital_Ratio, Institutional_Ownership, Delta_Institutional_Ownership, Net_Income)
```

```{r}
summary(data_reg_ready[c("Dividend_Dummy", "ShareRepurchase_Dummy", "ShareRepurchase_Amount", "Total_Assets", "Tier1Capital_Ratio", "Institutional_Ownership", "Delta_Institutional_Ownership")], digits = 1)
# output summary table to text file without using stargazer where variables are row names and columns are statistics including mean, max, min, etc.
# calculate summary stats for above variables (drop if we have NA)

# Drop any Delta changes more than 50% or less than -50%
data_reg_ready <- data_reg_ready %>%
  filter(Delta_Institutional_Ownership <= 0.5) %>%
  filter(Delta_Institutional_Ownership >= -0.5)

# winsorize total assets and tier1 capital ratio at 1% and 99% quantiles and institutional ownership variables at 1% and 99% too
data_reg_ready <- data_reg_ready %>%
  mutate(Total_Assets = ifelse(Total_Assets < quantile(Total_Assets, 0.01), quantile(Total_Assets, 0.01), ifelse(Total_Assets > quantile(Total_Assets, 0.99), quantile(Total_Assets, 0.99), Total_Assets)),
         Net_Income = ifelse(Net_Income < quantile(Net_Income, 0.01), quantile(Net_Income, 0.01), ifelse(Net_Income > quantile(Net_Income, 0.99), quantile(Net_Income, 0.99), Net_Income)),
         Tier1Capital_Ratio = ifelse(Tier1Capital_Ratio < quantile(Tier1Capital_Ratio, 0.01), quantile(Tier1Capital_Ratio, 0.01), ifelse(Tier1Capital_Ratio > quantile(Tier1Capital_Ratio, 0.99), quantile(Tier1Capital_Ratio, 0.99), Tier1Capital_Ratio)),
         Institutional_Ownership = ifelse(Institutional_Ownership < quantile(Institutional_Ownership, 0.01), quantile(Institutional_Ownership, 0.01), ifelse(Institutional_Ownership > quantile(Institutional_Ownership, 0.99), quantile(Institutional_Ownership, 0.99), Institutional_Ownership)),
         Delta_Institutional_Ownership = ifelse(Delta_Institutional_Ownership < quantile(Delta_Institutional_Ownership, 0.01), quantile(Delta_Institutional_Ownership, 0.01), ifelse(Delta_Institutional_Ownership > quantile(Delta_Institutional_Ownership, 0.99), quantile(Delta_Institutional_Ownership, 0.99), Delta_Institutional_Ownership)),
         )

sumstat <- data.frame(
  Variable = c("Dividend_Dummy","ShareRepurchase_Dummy", "Dividend_Amount", "ShareRepurchase_Amount", "Total_Assets", "Tier1Capital_Ratio", "Institutional_Ownership", "Delta_Institutional_Ownership"),
  Mean = c(mean(data_reg_ready$Dividend_Dummy), mean(data_reg_ready$ShareRepurchase_Dummy), mean(data_reg_ready$Dividend_Amount), mean(data_reg_ready$ShareRepurchase_Amount), mean(data_reg_ready$Total_Assets), mean(data_reg_ready$Tier1Capital_Ratio), mean(data_reg_ready$Institutional_Ownership), mean(data_reg_ready$Delta_Institutional_Ownership)),
  Median = c(median(data_reg_ready$Dividend_Dummy), median(data_reg_ready$ShareRepurchase_Dummy), median(data_reg_ready$Dividend_Amount), median(data_reg_ready$ShareRepurchase_Amount), median(data_reg_ready$Total_Assets), median(data_reg_ready$Tier1Capital_Ratio), median(data_reg_ready$Institutional_Ownership), median(data_reg_ready$Delta_Institutional_Ownership)),
  SD = c(sd(data_reg_ready$Dividend_Dummy), sd(data_reg_ready$ShareRepurchase_Dummy), sd(data_reg_ready$Dividend_Amount), sd(data_reg_ready$ShareRepurchase_Amount), sd(data_reg_ready$Total_Assets), sd(data_reg_ready$Tier1Capital_Ratio), sd(data_reg_ready$Institutional_Ownership), sd(data_reg_ready$Delta_Institutional_Ownership)),
  Min = c(min(data_reg_ready$Dividend_Dummy), min(data_reg_ready$ShareRepurchase_Dummy), min(data_reg_ready$Dividend_Amount), min(data_reg_ready$ShareRepurchase_Amount), min(data_reg_ready$Total_Assets), min(data_reg_ready$Tier1Capital_Ratio), min(data_reg_ready$Institutional_Ownership), min(data_reg_ready$Delta_Institutional_Ownership)),
  Max = c(max(data_reg_ready$Dividend_Dummy), max(data_reg_ready$ShareRepurchase_Dummy), max(data_reg_ready$Dividend_Amount), max(data_reg_ready$ShareRepurchase_Amount), max(data_reg_ready$Total_Assets), max(data_reg_ready$Tier1Capital_Ratio), max(data_reg_ready$Institutional_Ownership), max(data_reg_ready$Delta_Institutional_Ownership))
)
# print summary stats to console
print(sumstat)
# output summary stats to a text file and line the columns, save as one digit
write.table(sumstat, "../Results/ShareRepurchase_Summary.txt", sep = "\t", row.names = FALSE)
```
```{r}
# total net income summary stats
summary(data_reg_ready$Net_Income, digits = 1)

```

```{r}
stargazer(sumstat, type = "text", summary = FALSE, digits = 2, out = "../Results/ShareRepurchase_Summary.txt")
```

```{r}
# Order data by tic bank-name year quarter assets tier1 ratio institutional ownership, delta institution ownership, share repurchase dummy, and share repurchase amount
data_reg_ready_1 <- data_reg_ready %>%
  dplyr::select(tic, conm, fyearq, fqtr, Total_Assets, Net_Income, Tier1Capital_Ratio, Institutional_Ownership, Lag_Institutional_Ownership, Delta_Institutional_Ownership, ShareRepurchase_Dummy, ShareRepurchase_Amount)

# plot the histogram of the variables above
data_reg_ready_1 %>%
  gather(key = "variable", value = "value", -tic, -conm, -fyearq, -fqtr) %>%
  ggplot(aes(x = value)) +
  geom_histogram(bins = 30) +
  facet_wrap(~variable, scales = "free") +
  labs(title = "Histogram of Share Repurchase Variables",
       x = "Value",
       y = "Frequency")
```

```{r}
# Method 1: Two regressions in which in the first regression we regress the share repurchase dummy 
# on the average institutional ownership
# in the second regression we regress the share repurchase amount on the average institutional ownership 
# using only the subsample of those banks that issue share repurchase

# Regression 1: Share Repurchase Dummy on Average Institutional Ownership using data_reg_ready with atq and year-quarter FE (probit)
# generate a year-quarter variable from fyearq and fqtr
data_reg_ready <- data_reg_ready %>%
  mutate(yearq = paste(fyearq, fqtr, sep = "q")) %>% arrange(tic, yearq)

# generate size quintile based on total assets
data_reg_ready <- data_reg_ready %>%
  mutate(Size_Quintile = ntile(Total_Assets, 5))

# generate net income quintile
data_reg_ready <- data_reg_ready %>%
  mutate(Net_Income_Quintile = ntile(Net_Income, 5))

reg1 <- glm(ShareRepurchase_Dummy ~ Lag_Institutional_Ownership + log(Total_Assets) + log(Net_Income) + Tier1Capital_Ratio + factor(yearq), family = binomial(link = "probit"), data = data_reg_ready)

# Logit
reg1_1 <- glm(ShareRepurchase_Dummy ~ Lag_Institutional_Ownership + log(Total_Assets) + log(Net_Income) + Tier1Capital_Ratio + factor(yearq), family = binomial(link = "logit"), data = data_reg_ready)

### Dividend
reg1_div <- glm(Dividend_Dummy ~ Lag_Institutional_Ownership + log(Total_Assets) + log(Net_Income) + Tier1Capital_Ratio + factor(yearq), family = binomial(link = "probit"), data = data_reg_ready)
# Logit
reg1_1_div <- glm(Dividend_Dummy ~ Lag_Institutional_Ownership + log(Total_Assets) + log(Net_Income) + Tier1Capital_Ratio + factor(yearq), family = binomial(link = "logit"), data = data_reg_ready)

stargazer(reg1, reg1_1, reg1_div, reg1_1_div, type = "text", omit = "factor", out = "../Results/ShareRepurchase_Dividend_Dummy_Regression.txt")
```

```{r}
# New: Share Repurchase on Delta Institutional Ownership
reg1_delta <- lm(Delta_Institutional_Ownership ~ ShareRepurchase_Dummy + log(Total_Assets) + log(Net_Income) + Tier1Capital_Ratio + factor(yearq), data = data_reg_ready)
# Amount
reg1_delta_amount <- lm(Delta_Institutional_Ownership ~ ShareRepurchase_Amount + log(Total_Assets) + log(Net_Income) + Tier1Capital_Ratio + factor(yearq), data = data_reg_ready)

stargazer(reg1_delta, reg1_delta_amount, type = "text", omit = "factor", out = "../Results/Delta_Institutional_Ownership_Regression.txt")
```

```{r}
# Check for association between main variables
cor(data_reg_ready[c("ShareRepurchase_Dummy", "ShareRepurchase_Amount", "Total_Assets", "Tier1Capital_Ratio", "Institutional_Ownership", "Lag_Institutional_Ownership", "Delta_Institutional_Ownership")], use = "complete.obs")

# Check for coefficients of the probit model with no Institutional Ownership
reg1_no_inst <- glm(ShareRepurchase_Dummy ~ log(Total_Assets) + log(Net_Income) + Tier1Capital_Ratio + factor(yearq), family = binomial(link = "probit"), data = data_reg_ready)
reg1_no_tier1 <- glm(ShareRepurchase_Dummy ~ log(Total_Assets) + log(Net_Income) + Lag_Institutional_Ownership + factor(yearq), family = binomial(link = "probit"), data = data_reg_ready)
# Check whether results hold if using size quintile
reg1_quintile <- glm(ShareRepurchase_Dummy ~ Lag_Institutional_Ownership + Size_Quintile + Net_Income_Quintile + Tier1Capital_Ratio + factor(yearq), family = binomial(link = "probit"), data = data_reg_ready)
# Logit
reg1_1_quintile <- glm(ShareRepurchase_Dummy ~ Lag_Institutional_Ownership + Size_Quintile + Net_Income_Quintile + Tier1Capital_Ratio + factor(yearq), family = binomial(link = "logit"), data = data_reg_ready)
# Dividend Dummy
reg1_div_quintile <- glm(Dividend_Dummy ~ Lag_Institutional_Ownership + Size_Quintile + Net_Income_Quintile + Tier1Capital_Ratio + factor(yearq), family = binomial(link = "probit"), data = data_reg_ready)
# Logit
reg1_div_1_quintile <- glm(Dividend_Dummy ~ Lag_Institutional_Ownership + Size_Quintile + Net_Income_Quintile + Tier1Capital_Ratio + factor(yearq), family = binomial(link = "logit"), data = data_reg_ready)

# Dividend Dummy on the RHS
reg1_quintile_div <- glm(ShareRepurchase_Dummy ~ Dividend_Dummy + Lag_Institutional_Ownership + Size_Quintile + Net_Income_Quintile + Tier1Capital_Ratio + factor(yearq), family = binomial(link = "probit"), data = data_reg_ready)
# Logit
reg1_1_quintile_div <- glm(ShareRepurchase_Dummy ~ Dividend_Dummy + Lag_Institutional_Ownership + Size_Quintile + Net_Income_Quintile + Tier1Capital_Ratio + factor(yearq), family = binomial(link = "logit"), data = data_reg_ready)

# stargazer to output the regression results to a text file
stargazer(reg1, reg1_1, reg1_no_inst, reg1_no_tier1, type = "text", omit = "factor", out = "../Results/ShareRepurchase_Dummy_Regression.txt")
# stargazer reg1_quintile
stargazer(reg1_quintile, reg1_1_quintile, reg1_quintile_div, reg1_1_quintile_div, type = "text", omit = "factor", out = "../Results/ShareRepurchase_Dummy_Regression_Quintile.txt")
```

```{r}
stargazer(reg1_div_quintile, reg1_div_1_quintile, type = "text", omit = "factor", out = "../Results/Dividend_Dummy_Regression_Quintile.txt")
```

```{r}
# Get average marginal effects
library(margins)
library(sandwich)
library(lmtest)

cl_ccov_mat_check1 <- vcovCL(reg1_quintile_div, type = "HC1", cluster = data_reg_ready$yearq)
margins(reg1_quintile_div, data = data_reg_ready, at = list(Lag_Institutional_Ownership = mean(data_reg_ready$Lag_Institutional_Ownership), Size_Quintile = mean(data_reg_ready$Size_Quintile), Tier1Capital_Ratio = mean(data_reg_ready$Tier1Capital_Ratio)), vcov = cl_ccov_mat_check1, variables = c("Lag_Institutional_Ownership", "Size_Quintile", "Tier1Capital_Ratio"))
cl_ccov_mat_check2 <- vcovCL(reg1_1_quintile_div, type = "HC1", cluster = data_reg_ready$yearq)
margins(reg1_1_quintile_div, data = data_reg_ready, at = list(Lag_Institutional_Ownership = mean(data_reg_ready$Lag_Institutional_Ownership), Size_Quintile = mean(data_reg_ready$Size_Quintile), Tier1Capital_Ratio = mean(data_reg_ready$Tier1Capital_Ratio)), vcov = cl_ccov_mat_check2, variables = c("Lag_Institutional_Ownership", "Size_Quintile", "Tier1Capital_Ratio"))
```

```{r}

# Regression 2: Share Repurchase Amount on Average Institutional Ownership using data_reg_ready with atq and year FE
data_reg_ready_repur <- data_reg_ready %>%
  filter(ShareRepurchase_Amount > 0)
reg2 <- lm(ShareRepurchase_Amount ~ Lag_Institutional_Ownership + Size_Quintile + Tier1Capital_Ratio + factor(yearq), data = data_reg_ready_repur)
# Method 2: Use recursive methods as in CEO Ownership, Leasing, and Debt Financing
# Hamid Mehran, Robert A. Taggart and David Yermack
# Financial Management
# Vol. 28, No. 2 (Summer, 1999), pp. 5-14 (10 pages)

# Basically use the predicted value of the first regression as an explanatory variable in the second regression 
# Attach predicted to the data_reg_ready dataset
data_reg_ready <- data_reg_ready %>%
  mutate(predicted = predict(reg1_quintile))
reg3 <- lm(ShareRepurchase_Amount ~ Lag_Institutional_Ownership + Size_Quintile + Tier1Capital_Ratio + predicted + factor(yearq), data = data_reg_ready)
reg4 <- lm(ShareRepurchase_Amount ~ Lag_Institutional_Ownership + Size_Quintile + Tier1Capital_Ratio + factor(yearq), data = data_reg_ready)
# Use stargazer to generate regression table and don't show factor variables
stargazer(reg1_quintile, reg1_1_quintile, reg2, reg3, reg4, type = "text", omit = "factor", out = "../Results/ShareRepurchase_Regression.txt")
```

```{r}
# Get average marginal effects
library(margins)
library(sandwich)
library(lmtest)

cl_ccov_mat1 <- vcovCL(reg1, type = "HC1", cluster = data_reg_ready$yearq)
margins(reg1, data = data_reg_ready, at = list(Lag_Institutional_Ownership = mean(data_reg_ready$Lag_Institutional_Ownership), Total_Assets = mean(data_reg_ready$Total_Assets), Tier1Capital_Ratio = mean(data_reg_ready$Tier1Capital_Ratio)), vcov = cl_ccov_mat1, variables = c("Lag_Institutional_Ownership", "Total_Assets", "Tier1Capital_Ratio"))
cl_ccov_mat2 <- vcovCL(reg1_1, type = "HC1", cluster = data_reg_ready$yearq)
margins(reg1_1, data = data_reg_ready, at = list(Lag_Institutional_Ownership = mean(data_reg_ready$Lag_Institutional_Ownership), Total_Assets = mean(data_reg_ready$Total_Assets), Tier1Capital_Ratio = mean(data_reg_ready$Tier1Capital_Ratio)), vcov = cl_ccov_mat2, variables = c("Lag_Institutional_Ownership", "Total_Assets", "Tier1Capital_Ratio"))
cl_ccov_mat3 <- vcovCL(reg2, type = "HC1", cluster = data_reg_ready_repur$yearq)
reg2coeffs_cl <- coeftest(reg2, vcov = cl_ccov_mat3)
reg2coeffs_cl
```

```{r}
# Re-run the regressions by splitting the sample by before/after 2010
data_reg_ready_2010 <- data_reg_ready %>%
  filter(fyearq < 2010)
data_reg_ready_repur_2010 <- data_reg_ready_repur %>%
  filter(fyearq < 2010)
data_reg_ready_after_2010 <- data_reg_ready %>%
  filter(fyearq >= 2010)
data_reg_ready_repur_after_2010 <- data_reg_ready_repur %>%
  filter(fyearq >= 2010)

# Regression 1: Share Repurchase Dummy on Average Institutional Ownership using data_reg_ready with atq and year-quarter FE (probit)
reg1_2010 <- glm(ShareRepurchase_Dummy ~ Lag_Institutional_Ownership + Size_Quintile + Tier1Capital_Ratio + factor(yearq), family = binomial(link = "probit"), data = data_reg_ready_2010)
reg1_after_2010 <- glm(ShareRepurchase_Dummy ~ Lag_Institutional_Ownership + Size_Quintile + Tier1Capital_Ratio + factor(yearq), family = binomial(link = "probit"), data = data_reg_ready_after_2010)
reg2_2010_amount <- lm(ShareRepurchase_Amount ~ Lag_Institutional_Ownership + Size_Quintile + Tier1Capital_Ratio + factor(yearq), data = data_reg_ready_repur_2010)
reg2_after_2010_amount <- lm(ShareRepurchase_Amount ~ Lag_Institutional_Ownership + Size_Quintile + Tier1Capital_Ratio + factor(yearq), data = data_reg_ready_repur_after_2010)
# output in table
stargazer(reg1_2010, reg1_after_2010, reg2_2010_amount, reg2_after_2010_amount, type = "text", omit = "factor", out = "../Results/ShareRepurchase_Regression_2010.txt")
``` 

```{r}
# Do the same regressions for subsamples (G-SIB, Large, and Regional Banks) using a for loop that loops for each
size_buckets <- unique(data_reg_ready$size_prev_quarter)
# Regional
data_reg_ready_regional <- data_reg_ready %>%
  filter(size_prev_quarter == "Regional")
data_reg_ready_repur_regional <- data_reg_ready_repur %>%
  filter(size_prev_quarter == "Regional")
reg1_regional <- glm(ShareRepurchase_Dummy ~ Lag_Institutional_Ownership + Tier1Capital_Ratio + factor(yearq), family = binomial(link = "probit"), data = data_reg_ready_regional)
reg2_regional <- lm(ShareRepurchase_Amount ~ Lag_Institutional_Ownership + Tier1Capital_Ratio + factor(yearq), data = data_reg_ready_repur_regional)
# Large
data_reg_ready_large <- data_reg_ready %>%
  filter(size_prev_quarter == "Large")
data_reg_ready_repur_large <- data_reg_ready_repur %>%
  filter(size_prev_quarter == "Large")
reg1_large <- glm(ShareRepurchase_Dummy ~ Lag_Institutional_Ownership + Tier1Capital_Ratio + factor(yearq), family = binomial(link = "probit"), data = data_reg_ready_large)
reg2_large <- lm(ShareRepurchase_Amount ~ Lag_Institutional_Ownership + Tier1Capital_Ratio + factor(yearq), data = data_reg_ready_repur_large)
# G-SIB
data_reg_ready_gsib <- data_reg_ready %>%
  filter(size_prev_quarter == "G-SIB")
data_reg_ready_repur_gsib <- data_reg_ready_repur %>%
  filter(size_prev_quarter == "G-SIB")
reg1_gsib <- glm(ShareRepurchase_Dummy ~ Lag_Institutional_Ownership + Tier1Capital_Ratio + factor(yearq), family = binomial(link = "probit"), data = data_reg_ready_gsib)
reg2_gsib <- lm(ShareRepurchase_Amount ~ Lag_Institutional_Ownership + Tier1Capital_Ratio + factor(yearq), data = data_reg_ready_repur_gsib)
# output in table
stargazer(reg1_regional, reg2_regional, reg1_large, reg2_large, type = "text", omit = "factor", out = "../Results/ShareRepurchase_Regression_BySize.txt")
```

```{r}
# Output the same results but for large+gsib banks
data_reg_ready_large_gsib <- data_reg_ready %>%
  filter(size_prev_quarter != "Regional")
data_reg_ready_repur_large_gsib <- data_reg_ready_repur %>%
  filter(size_prev_quarter != "Regional")
reg1_large_gsib <- glm(ShareRepurchase_Dummy ~ Lag_Institutional_Ownership + Tier1Capital_Ratio + factor(yearq), family = binomial(link = "probit"), data = data_reg_ready_large_gsib)
reg2_large_gsib <- lm(ShareRepurchase_Amount ~ Lag_Institutional_Ownership + Tier1Capital_Ratio + factor(yearq), data = data_reg_ready_repur_large_gsib)
# output in table
stargazer(reg1_gsib, reg2_gsib, reg1_large_gsib, reg2_large_gsib, type = "text", omit = "factor", out = "../Results/ShareRepurchase_Regression_Large_GSIB.txt")
# Output the same results but for large+gsib banks and split based on before/after 2010
data_reg_ready_large_gsib_2010 <- data_reg_ready_large_gsib %>%
  filter(fyearq < 2010)
data_reg_ready_repur_large_gsib_2010 <- data_reg_ready_repur_large_gsib %>%
  filter(fyearq < 2010)
data_reg_ready_large_gsib_after_2010 <- data_reg_ready_large_gsib %>%
  filter(fyearq >= 2010)
data_reg_ready_repur_large_gsib_after_2010 <- data_reg_ready_repur_large_gsib %>%
  filter(fyearq >= 2010)
reg1_large_gsib_2010 <- glm(ShareRepurchase_Dummy ~ Lag_Institutional_Ownership + Tier1Capital_Ratio + factor(yearq), family = binomial(link = "probit"), data = data_reg_ready_large_gsib_2010)
reg2_large_gsib_2010 <- lm(ShareRepurchase_Amount ~ Lag_Institutional_Ownership + Tier1Capital_Ratio + factor(yearq), data = data_reg_ready_repur_large_gsib_2010)
reg1_large_gsib_after_2010 <- glm(ShareRepurchase_Dummy ~ Lag_Institutional_Ownership + Tier1Capital_Ratio + factor(yearq), family = binomial(link = "probit"), data = data_reg_ready_large_gsib_after_2010)
reg2_large_gsib_after_2010 <- lm(ShareRepurchase_Amount ~ Lag_Institutional_Ownership + Tier1Capital_Ratio + factor(yearq), data = data_reg_ready_repur_large_gsib_after_2010)
# output in table
stargazer(reg1_large_gsib_2010, reg2_large_gsib_2010, type = "text", omit = "factor", out = "../Results/ShareRepurchase_Regression_Large_GSIB_Before2010.txt")
stargazer(reg1_large_gsib_after_2010, reg2_large_gsib_after_2010, type = "text", omit = "factor", out = "../Results/ShareRepurchase_Regression_Large_GSIB_After2010.txt")
```
